'use client';
import { useEffect, useRef, useState } from 'react';
import { Map, Volume2, VolumeX, Maximize, HelpCircle, Navigation, MessageCircle, Footprints, ChevronRight, Landmark, ArrowUp, ArrowDown, ArrowLeft, ArrowRight } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import type { Game, GameState } from '@/lib/game';
import { registerGameTools } from '@/lib/webmcp';
import { destinations, npcs, sources, floors, type Place } from '@/lib/world-data';

export default function Home() {
  const mount=useRef<HTMLDivElement>(null), game=useRef<Game|null>(null);
  const [state,setState]=useState<GameState>({location:'South Lawn',zone:'grounds',x:0,z:38,heading:0,nearby:null,visited:[],met:[]});
  const [panel,setPanel]=useState<'map'|'help'|'moves'|null>(null),[mapFloor,setMapFloor]=useState<Place>('grounds');
  const [conversation,setConversation]=useState<string|null>(null),[line,setLine]=useState(-1);
  const [muted,setMuted]=useState(true),[error,setError]=useState(''),[ready,setReady]=useState(false),[welcome,setWelcome]=useState(true);
  useEffect(()=>{let cancelled=false;let unregister=()=>{};import('@/lib/game').then(({Game})=>{if(cancelled||!mount.current)return;try{game.current=new Game(mount.current,s=>{setState(s);if(s.zone!=='grounds'||Math.hypot(s.x,s.z-38)>.5)setWelcome(false);},id=>{setConversation(id);setLine(-1);},()=>setPanel(p=>p==='map'?null:'map'));game.current.pause(true);unregister=registerGameTools(game.current,id=>{game.current?.travel(id);setPanel(null);setConversation(null);setWelcome(false);});void Promise.all([game.current.loadPlayer(),game.current.loadArchitecture(),game.current.loadStaff()]).then(()=>{if(!cancelled)setReady(true);}).catch(()=>{if(!cancelled)setError('The game models could not load. Refresh to try again.');});}catch{setError('The 3D scene could not start. Enable hardware acceleration or try a browser with WebGL 2 support.');}}).catch(()=>setError('The game could not load. Refresh to try again.'));return()=>{cancelled=true;unregister();game.current?.dispose();game.current=null;};},[]);
  useEffect(()=>{game.current?.pause(Boolean(panel||conversation||!ready));},[panel,conversation,ready]);
  const travel=(id:string)=>{game.current?.travel(id);setPanel(null);setWelcome(false);};
  const person=npcs.find(n=>n.id===conversation);
  const interact=()=>{setWelcome(false);game.current?.interact();};
  return <main className="game-shell">
    <div ref={mount} className="world" aria-label="3D White House game. WASD moves, drag looks around, E interacts."/><div className="vignette"/>
    <header className="topbar"><div className="brand"><Landmark size={29}/><div><h1>THE WHITE HOUSE</h1><p>FREE ROAM <span>•</span> AN UNOFFICIAL ADVENTURE</p></div></div><div className="compass"><span>W</span><i/><span>{['N','NE','E','SE','S','SW','W','NW'][Math.round((((state.heading*180/Math.PI)%360)+360)%360/45)%8]}</span><i/><span>E</span><b>◆</b></div><nav aria-label="Game controls"><button aria-label="Dance and gestures" onClick={()=>setPanel('moves')}>Moves</button><button aria-label="Open map" onClick={()=>{setMapFloor(state.zone);setPanel('map');}}><Map size={20}/><span>Map</span><kbd>M</kbd></button><button aria-label={muted?'Enable ambient sound':'Mute ambient sound'} onClick={()=>{setMuted(!muted);game.current?.sound(muted);}}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><button aria-label="Full screen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});else void document.documentElement.requestFullscreen?.().catch(()=>{});}}><Maximize size={18}/></button><button aria-label="Controls and sources" onClick={()=>setPanel('help')}><HelpCircle size={19}/></button></nav></header>
    <section className="location"><div className="eyebrow"><span className="live-dot"/> {state.zone==='grounds'?'EXPLORING THE GROUNDS':'INSIDE THE WHITE HOUSE'}</div><h2>{state.location}</h2><p>{floors.find(f=>f.id===state.zone)?.label}<span> / </span>Washington, D.C.</p></section>
    {welcome&&ready&&<aside className="welcome"><div className="eyebrow">WELCOME, MR. PRESIDENT</div><h3>A little time to roam.</h3><p>Walk the lawns, step inside the residence, or see how the ballroom is coming along.</p><button onClick={()=>{setWelcome(false);game.current?.focus();}}>Let’s take a walk <ChevronRight size={17}/></button><small>W A S D to walk · Drag to look around</small></aside>}
    {!ready&&!error&&<div className="loading"><Landmark size={32}/><h2>Opening the gates…</h2><p>Preparing your White House visit.</p></div>}
    {error&&<div className="loading"><h2>Unable to open the game</h2><p>{error}</p><button onClick={()=>window.location.reload()}>Try again</button></div>}
    {state.nearby&&!panel&&!conversation&&<button className="interact" aria-label={`${state.nearby.kind==='npc'?'Talk to':'Explore'} ${state.nearby.label}`} onClick={interact}><kbd>E</kbd><div><small>{state.nearby.kind==='npc'?'START A CONVERSATION':'EXPLORE'}</small><strong>{state.nearby.label}</strong></div>{state.nearby.kind==='npc'?<MessageCircle size={22}/>:<ChevronRight size={22}/>}</button>}
    <div className="bottom-left"><div className="player-card"><span className="player-number">47</span><div><small>PLAYING AS</small><strong>Donald J. Trump</strong><span className="player-mode"><span/> Free to explore</span></div></div><div className="progress-text"><Footprints size={15}/>{state.visited.length} places discovered<span>·</span><MessageCircle size={15}/>{state.met.length} people met</div></div>
    <button className="minimap" aria-label="Open travel map" onClick={()=>{setMapFloor(state.zone);setPanel('map');}}><div className="minimap-top"><span>{state.zone==='grounds'?'WHITE HOUSE GROUNDS':floors.find(f=>f.id===state.zone)?.label}</span><Navigation size={13}/></div><GameMap zone={state.zone} state={state}/><div className="minimap-bottom"><span><i/> You</span><span>Expand <kbd>M</kbd></span></div></button>
    <footer className="control-strip"><span><kbd>W A S D</kbd>Move</span><span><kbd>DRAG</kbd>Look</span><span><kbd>SHIFT</kbd>Run</span><span><kbd>SPACE</kbd>Jump</span><span><kbd>E</kbd>Interact</span><span className="build-label">PUBLIC-PLAN ADAPTATION</span></footer>
    <div className="touch-pad" aria-label="Touch movement">{[['KeyW',ArrowUp],['KeyA',ArrowLeft],['KeyS',ArrowDown],['KeyD',ArrowRight]].map(([key,Icon])=>{const C=Icon as typeof ArrowUp;return <button key={key as string} className={key as string} aria-label={`Move ${key==='KeyW'?'forward':key==='KeyS'?'back':key==='KeyA'?'left':'right'}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setWelcome(false);game.current?.key(key as string,true);}} onPointerUp={()=>game.current?.key(key as string,false)} onPointerCancel={()=>game.current?.key(key as string,false)} onLostPointerCapture={()=>game.current?.key(key as string,false)}><C size={24}/></button>;})}</div><div className="touch-actions"><button onClick={()=>game.current?.jump()}>Jump</button><button onClick={interact}>E</button></div>
    <Dialog open={Boolean(panel)} onOpenChange={open=>{if(!open)setPanel(null);}}><DialogContent className="game-dialog map-dialog"><DialogTitle>{panel==='moves'?'Make a move':panel==='help'?'Field guide':'Explore the White House'}</DialogTitle><DialogDescription>{panel==='moves'?'Choose an animation. Start walking to stop dancing.':panel==='help'?'Controls, cast, and architectural references.':'Choose a destination to travel there, or close the map and keep walking.'}</DialogDescription>
    {panel==='moves'?<div className="dialogue-options">{([['dance','Rally dance','G'],['ymca','YMCA dance','Y'],['victory','Victory fist pump','V'],['backflip','Backflip','B']] as const).map(([id,label,key])=><button key={id} onClick={()=>{setPanel(null);setWelcome(false);game.current?.emote(id);game.current?.focus();}}><kbd>{key}</kbd>{label}<ChevronRight size={16}/></button>)}<button onClick={()=>{setPanel(null);game.current?.emote(null);}}>Stop animation</button><p>Hold C while moving to stroll. Shift runs; Shift + C sprints.</p></div>:panel==='map'?<Tabs value={mapFloor} onValueChange={value=>setMapFloor(value as Place)}><TabsList className="floor-buttons">{floors.map(f=><TabsTrigger value={f.id} key={f.id} className={mapFloor===f.id?'selected':''} >{f.label}</TabsTrigger>)}</TabsList><TabsContent value={mapFloor}><p className="map-progress">{state.visited.length} places discovered &middot; {state.met.length} people met</p><div className="map-layout"><div className="large-map"><GameMap zone={mapFloor} state={state} onTravel={travel}/><span className="map-caption">N ↑ · Schematic game layout · Not to scale</span></div><div className="destination-list">{destinations.filter(d=>d.zone===mapFloor).map(d=><button key={d.id} onClick={()=>travel(d.id)}><div><strong>{d.name}</strong><small>{d.description}</small></div><ChevronRight size={17}/></button>)}</div></div></TabsContent></Tabs>:<div className="guide"><h3>Make yourself at home</h3><p>WASD or arrow keys move. Hold Shift to run, C to stroll, or Shift + C to sprint. Space jumps. G starts the rally dance, Y the YMCA dance, V a victory fist pump, and B a backflip. Move or press Escape to stop a gesture. The Moves button works on touchscreens. Drag the scene to turn the camera; Q / R also turn. E talks to nearby people, opens entrances, and uses stairs. M opens the travel map. On a phone, use the directional pad and drag the scene to look.</p><h3>A game inspired by public plans</h3><p>This is an unofficial, fictional game. Exterior relationships and major room positions follow public historical plans. Dimensions, doorways, furnishings, upper-floor spaces, and construction staging are simplified for play. It is not a current, measured blueprint or a live depiction of the construction site. Conversations are invented; the cast includes current and former second-administration officials.</p><h3>Architectural references</h3>{sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>)}<h3>Explore freely</h3><p>The entire modeled outdoor estate is open, including both lawns, gardens, the pool, putting green and ballroom worksite. Enter the residence and West Wing at glowing door markers. Use the map to jump to any modeled room. There are no locked areas or timed missions.</p></div>}
    </DialogContent></Dialog>
    <Dialog open={Boolean(person)} onOpenChange={open=>{if(!open)setConversation(null);}}><DialogContent className="game-dialog conversation-dialog"><div className="conversation-tag">WHITE HOUSE CONVERSATIONS<span>FICTIONAL DIALOGUE</span></div><DialogTitle>{person?.name}</DialogTitle><DialogDescription>{person?.role}</DialogDescription><p className="dialogue-line">{line<0?person?.greeting:person?.topics[line]?.answer}</p><div className="dialogue-options">{person?.topics.map((t,i)=><button key={t.question} onClick={()=>setLine(i)}><span>{i+1}</span>{t.question}<ChevronRight size={16}/></button>)}<button onClick={()=>setConversation(null)}><span>↩</span>I’ll keep exploring.</button></div></DialogContent></Dialog>
  </main>;
}
function GameMap({zone,state,onTravel}:{zone:Place;state:GameState;onTravel?:(id:string)=>void}){
 const ground=zone==='grounds';return <svg viewBox={ground?'-108 -103 216 242':zone==='west'?'-30 -43 130 72':'-31 -22 62 44'} className="map-svg" role="img" aria-label={`${zone} game map`}><rect x={ground?-108:-31} y={ground?-103:zone==='west'?-43:-22} width={ground?216:zone==='west'?130:62} height={ground?242:zone==='west'?72:44} fill="#132f30"/>
 {ground?<g fill="none" stroke="#71948a" strokeWidth="1"><rect x="-100" y="-96" width="200" height="225" rx="25"/><ellipse cx="0" cy="-62" rx="38" ry="22"/><ellipse cx="0" cy="56" rx="60" ry="46"/><path d="M-52 -36 H52 M-25 -23 H-42 M25 -23 H42 M0 10 V28 M0 104 V126"/><rect x="-25" y="-38" width="50" height="30" fill="#aac0b0"/><rect x="-74" y="-38" width="32" height="36" fill="#78998f"/><rect x="-43" y="-35" width="18" height="8" fill="#78998f"/><rect x="42" y="-40" width="39" height="47" stroke="#dda854" strokeDasharray="2 2"/><rect x="-43" y="1" width="24" height="17" fill="#426f59"/><rect x="24" y="8" width="23" height="14" fill="#426f59"/><ellipse cy="-7" rx="8" ry="7" fill="#aac0b0"/><circle cy="48" r="6"/><circle cy="-63" r="5"/><rect x="-78" y="38" width="13" height="25" fill="#5d999b"/></g>:<g stroke="#95b5ad" strokeWidth=".3" fill="#35615a">{destinations.filter(d=>d.zone===zone&&d.room).map(d=>d.room!.style==='oval'?<ellipse key={d.id} cx={d.x} cy={d.z} rx={d.room!.w/2} ry={d.room!.d/2}/>:<rect key={d.id} x={d.x-d.room!.w/2} y={d.z-d.room!.d/2} width={d.room!.w} height={d.room!.d}/>)}</g>}
 {onTravel&&destinations.filter(d=>d.zone===zone).map(d=><g key={d.id} className="map-point" role="button" tabIndex={0} aria-label={`Travel to ${d.name}`} onClick={()=>onTravel(d.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onTravel(d.id);}}}><circle cx={d.x} cy={d.z} r={ground?3.5:1.1} fill="#e7bd65"/><title>{d.name}</title><text x={d.x} y={d.z+(ground?8:2.5)} textAnchor="middle" fill="#f5f2dc" fontSize={ground?3.8:1.45}>{d.short??d.name}</text></g>)}
 {state.zone===zone&&<g transform={`translate(${state.x} ${state.z}) rotate(${state.heading*180/Math.PI})`}><circle r={ground?5:1.5} fill="#f3ca72" opacity=".18"/><path d={ground?'M0 -4 L3 4 L0 2 L-3 4 Z':'M0 -1.2 L.9 1.2 L0 .6 L-.9 1.2 Z'} fill="#ffda80"/></g>}</svg>;
}



