import type {ControllerStatus} from '@/lib/controller';

export function ControllerGuide({status}:{status?:ControllerStatus}){
 const current=status??{state:'none',name:'',axes:[],buttons:[]};
 const message={none:'No controller detected. Connect it, press a button, then release it.',unavailable:'This browser is not providing controller access.',unmapped:'Controller detected, but this browser has not provided a standard button layout.',release:'Release the sticks, triggers, and buttons to enable controls.',ready:'Controller connected and ready.'}[current.state];
 return <section className="controller-guide"><h3>Controller & Tesla setup</h3><p role="status">{message}</p>{current.name&&<small className="controller-name">{current.name}</small>}
 {current.name&&<div className="controller-check" aria-label="Live controller input"><span>Stick check</span>{current.axes.map((v,i)=><meter key={i} min={-1} max={1} value={v} aria-label={`Stick axis ${i+1}`}/>)}<span>Buttons: {current.buttons.length?current.buttons.map(i=>i+1).join(', '):'released'}</span></div>}
 <dl className="controller-bindings"><dt>Left stick</dt><dd>Walk · steer and drive the cart</dd><dt>Right stick</dt><dd>Look around · aim</dd><dt>A / Cross</dt><dd>Jump · rise with jetpack · select in menus</dd><dt>B / Circle</dt><dd>Cart handbrake · descend · close menus</dd><dt>X / Square</dt><dd>Interact · get in or out of the cart</dd><dt>Y / Triangle</dt><dd>Switch camera</dd><dt>RT / R2</dt><dd>Cart accelerator · fire blaster</dd><dt>LT / L2</dt><dd>Brake into reverse</dd><dt>RB / R1 or L3</dt><dd>Hold to run or boost</dd><dt>LB / L1</dt><dd>Use race item · toggle flight guide</dd><dt>D-pad up</dt><dd>Recover cart during a race</dd><dt>Menu / Options</dt><dd>Open Play / pause · close menu</dd><dt>View / Share</dt><dd>Open travel map</dd><dt>D-pad / left stick</dt><dd>Navigate menus; A / Cross selects</dd></dl>
 <p>In your parked Tesla, open this game in the browser after connecting a compatible controller. Press a button, then release it. The live check above confirms whether this browser receives it. A controller working in Tesla Arcade does not necessarily work in the browser.</p><p>The car’s built-in steering wheel and pedals are not supported by this web game. Touch controls remain available if the browser does not report a gamepad. <a href="https://www.tesla.com/ownersmanual/modely/en_us/GUID-79A49D40-A028-435B-A7F6-8E48846AB9E9.html" target="_blank" rel="noreferrer">Tesla controller connection guide ↗</a></p></section>;
}
