'use client';
import {useEffect,useRef,useState,useSyncExternalStore,type CSSProperties} from 'react';
import {Activity,ArrowRight,Check,Clock3,Pause,Play,Radio,RotateCcw,ShieldCheck,Siren,Truck,Zap} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {AGENCIES,SCENARIOS,SituationChallenge,type Agency,type ScenarioId,type SituationState} from '@/lib/situation-game';
const icons={rescue:Siren,power:Zap,logistics:Truck};
const stamp=(s:number)=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const readBest=()=>{try{return Math.max(0,Number(localStorage.getItem('wh-situation-best'))||0);}catch{return 0;}};
const subscribeBest=(changed:()=>void)=>{window.addEventListener('storage',changed);window.addEventListener('wh-situation-best',changed);return()=>{window.removeEventListener('storage',changed);window.removeEventListener('wh-situation-best',changed);};};
export function SituationControls({open,onClose,onFeed}:{open:boolean;onClose:()=>void;onFeed:(state:SituationState)=>void}){
 const [engine]=useState(()=>new SituationChallenge());
 const dialog=useRef<HTMLDivElement>(null);
 const [state,setState]=useState(()=>engine.snapshot()),[paused,setPaused]=useState(false),[selected,setSelected]=useState('harbor');
 const best=useSyncExternalStore(subscribeBest,readBest,()=>0);
 const feed=useRef(onFeed);useEffect(()=>{feed.current=onFeed;},[onFeed]);
 const sync=()=>{const next=engine.snapshot();setState(next);feed.current(next);};
 useEffect(()=>{
  if(!open||paused||state.phase!=='running')return;
  let last=performance.now();
  const timer=window.setInterval(()=>{const now=performance.now();if(document.hidden){last=now;return;}engine.update((now-last)/1000);last=now;const next=engine.snapshot();setState(next);feed.current(next);},200);
  const suspend=()=>{setPaused(true);};
  window.addEventListener('blur',suspend);document.addEventListener('visibilitychange',suspend);
  return()=>{clearInterval(timer);window.removeEventListener('blur',suspend);document.removeEventListener('visibilitychange',suspend);};
 },[open,paused,state.phase,engine]);
 useEffect(()=>{if(state.phase!=='won'||state.score<=best)return;try{localStorage.setItem('wh-situation-best',String(state.score));window.dispatchEvent(new Event('wh-situation-best'));}catch{}},[state.phase,state.score,best]);
 const scenario=SCENARIOS.find(s=>s.id===state.scenario)!,active=state.incidents.filter(i=>i.status==='active'),chosen=active.find(i=>i.id===selected)??active[0],finished=state.phase==='won'||state.phase==='lost';
 useEffect(()=>{if(!open)return;const root=dialog.current,focused=document.activeElement as HTMLButtonElement|null;if(root&&(!root.contains(focused)||focused?.disabled)){const next=state.phase==='running'?(root.querySelector<HTMLButtonElement>('.dispatch-agencies button:not(:disabled)')??root.querySelector<HTMLButtonElement>('.incident-card[aria-pressed="true"], .command-pause')):root.querySelector<HTMLButtonElement>('.command-primary');next?.focus({preventScroll:true});}},[open,state.phase,state.teams]);
 const selectScenario=(id:ScenarioId)=>{engine.reset(id);setSelected(SCENARIOS.find(s=>s.id===id)!.plans[0].id);setPaused(false);sync();};
 const dispatch=(agency:Agency)=>{if(paused||!chosen)return;engine.dispatch(chosen.id,agency);sync();};
 const next=state.incidents.find(i=>i.status==='pending');
 return <Dialog open={open} onOpenChange={value=>{if(!value)onClose();}}><DialogContent ref={dialog} className="situation-dialog" showCloseButton={false}>
  <header className="command-header"><div><span className="command-eyebrow"><Radio size={15}/> WHITE HOUSE · FICTIONAL RESPONSE EXERCISE</span><DialogTitle>Situation Room</DialogTitle><DialogDescription>{state.phase==='briefing'?'Take the chair. Make the call.':scenario.title+' · '+scenario.difficulty}</DialogDescription></div><button onClick={onClose} className="command-exit">{state.phase==='running'?'Pause & leave':'Leave room controls'} <ArrowRight size={16}/></button></header>
  {state.phase==='briefing'?<div className="command-briefing">
   <div className="command-scenarios">{SCENARIOS.map((s,i)=><button className={s.id===state.scenario?'selected':''} aria-pressed={s.id===state.scenario} key={s.id} onClick={()=>selectScenario(s.id)}><span>0{i+1}</span><div><strong>{s.title}</strong><small>{s.difficulty}</small></div><ArrowRight size={20}/></button>)}</div>
   <section className="command-mission"><span className="command-eyebrow">YOUR BRIEFING</span><h2>{scenario.title}</h2><p>{scenario.brief}</p><div className="mission-facts"><span><Clock3/>{stamp(scenario.duration)} shift</span><span><Radio/>6 response teams</span><span><Activity/>{scenario.plans.length} incidents</span></div><ol><li>Select an incident, then dispatch the teams it needs.</li><li>Teams travel for 3 seconds, work, then return. Each agency has two teams.</li><li>Contain every incident before its urgency reaches 100%. Use your two Federal Surges when the board gets busy.</li></ol><button className="command-primary" onClick={()=>{engine.start();setPaused(false);sync();}}>Begin briefing <Play size={18}/></button>{best>0&&<small className="command-record">Personal best · {best.toLocaleString()} points</small>}</section>
  </div>:finished?<section className="command-debrief"><ShieldCheck size={48}/><span className="command-eyebrow">END OF SHIFT</span><h2>{state.phase==='won'?'Crisis contained.':'A difficult night.'}</h2><p>{state.phase==='won'?'Every incident is under control. Your response teams are heading home.':state.confidence<=0?'Too many response windows were missed. Dispatch early and use the surge before urgency peaks.':'Some incidents remained unresolved. Keep both teams from each agency working and watch for returning crews.'}</p><div className="debrief-stats"><div><strong>{state.score.toLocaleString()}</strong><span>points</span></div><div><strong>{state.resolved}/{state.total}</strong><span>contained</span></div><div><strong>{stamp(state.elapsed)}</strong><span>elapsed</span></div></div><p className="command-record">Personal best · {Math.max(best,state.phase==='won'?state.score:0).toLocaleString()}</p><div className="command-result-actions"><button className="command-primary" onClick={()=>{engine.reset();engine.start();setPaused(false);sync();}}><RotateCcw size={18}/> Play again</button><button onClick={()=>selectScenario(state.scenario)}>Choose another scenario</button><button onClick={onClose}>Explore the room</button></div></section>:<>
   <div className="command-telemetry"><div><small>TIME LEFT</small><strong>{stamp(Math.max(0,state.duration-state.elapsed))}</strong></div><div><small>CONTAINED</small><strong>{state.resolved}<em> / {state.total}</em></strong></div><div><small>PUBLIC CONFIDENCE</small><strong>{Math.round(state.confidence)}<em>%</em></strong></div><div><small>SCORE</small><strong>{state.score.toLocaleString()}</strong></div><button className="command-pause" onClick={()=>setPaused(!paused)} aria-label={paused?'Resume exercise':'Pause exercise'}>{paused?<Play/>:<Pause/>}<span>{paused?'Resume':'Pause'}</span></button></div>
   {paused&&<div className="command-paused">Exercise paused. Your teams and incident timers are on hold. <button onClick={()=>setPaused(false)}>Resume</button></div>}
   <div className="command-board">
    <section className="command-incidents"><div className="command-section-title"><h2>Incident board</h2><span>{active.length} active</span></div><div className="command-incident-list">{active.map(i=>{const work=Object.values(i.needs).reduce((a,b)=>a+b,0),left=Object.values(i.remaining).reduce((a,b)=>a+b,0);return <button key={i.id} onClick={()=>setSelected(i.id)} aria-pressed={chosen?.id===i.id} className={'incident-card'+(chosen?.id===i.id?' selected':'')+(i.severity>72?' urgent':'')}><span className="incident-meta">{i.region}<b>{Math.ceil(i.severity)}% urgency</b></span><strong>{i.title}</strong><span className="incident-needs">{(Object.keys(i.needs) as Agency[]).map(a=>{const Icon=icons[a],assigned=state.teams.some(t=>t.incident===i.id&&t.agency===a);return <span key={a} style={{color:AGENCIES[a].color}}><Icon size={14}/>{i.remaining[a]===0?'Done':assigned?'Assigned':AGENCIES[a].short}</span>;})}</span><progress className="incident-progress" aria-label={`${i.title} response progress`} max={100} value={Math.round((1-left/work)*100)}/></button>;})}{!active.length&&<div className="command-clear"><ShieldCheck/><strong>Current incidents contained</strong><p>{next?`Next report in ${Math.ceil(next.at-state.elapsed)} seconds. Teams are returning.`:'Completing the shift…'}</p></div>}</div></section>
    <section className="command-dispatch"><div className="command-section-title"><h2>Dispatch desk</h2><span>{next?`Next report · ${Math.max(0,Math.ceil(next.at-state.elapsed))}s`:'All reports received'}</span></div>{chosen?<><span className="command-eyebrow">{chosen.region}</span><h3>{chosen.title}</h3><p>{chosen.brief}</p><div className="command-urgency"><span>Urgency <b>{Math.ceil(chosen.severity)}%</b></span><div><i style={{width:`${chosen.severity}%`,background:chosen.severity>72?'#ff937e':'#ebca7d'}}/></div></div><div className="dispatch-agencies">{(Object.keys(AGENCIES) as Agency[]).map(a=>{const Icon=icons[a],free=state.teams.filter(t=>t.agency===a&&!t.incident&&t.returning<=0).length,team=state.teams.find(t=>t.agency===a&&t.incident===chosen.id),required=(chosen.remaining[a]??0)>0,eta=chosen.remaining[a]??0;return <button key={a} style={{'--agency':AGENCIES[a].color} as CSSProperties} disabled={paused||!required||!!team||!free} onClick={()=>dispatch(a)}><Icon size={23}/><div><strong>{AGENCIES[a].name}</strong><small>{!chosen.needs[a]?'Not needed here':!required?'Assignment complete':team?team.travel>0?`En route · ${Math.ceil(team.travel)}s`:`Working · ${Math.ceil(eta-Math.min(state.surgeTime,eta/2))}s remaining`:`${free} of 2 available · ${Math.ceil(eta)}s work`}</small></div>{!required&&chosen.needs[a]?<Check/>:<span>{team?'Assigned':free&&required?'Send →':'—'}</span>}</button>;})}</div></>:<p>Select an incident when it appears on the board.</p>}
     <button className="command-surge" disabled={paused||state.surges===0||state.surgeTime>0} onClick={()=>{engine.surge();sync();}}><Zap/><div><strong>{state.surgeTime>0?`Federal Surge · ${Math.ceil(state.surgeTime)}s`:'Authorize Federal Surge'}</strong><small>{state.surgeTime>0?'Teams work twice as fast; urgency is held.':`Double response speed for 12 seconds · ${state.surges} left`}</small></div></button>
    </section>
   </div>
   <footer className="command-footer"><div className="command-team-strip">{(Object.keys(AGENCIES) as Agency[]).map(a=><span key={a}><b style={{color:AGENCIES[a].color}}>{AGENCIES[a].short}</b>{state.teams.filter(t=>t.agency===a).map(t=><i key={t.id} className={t.incident?'busy':t.returning>0?'returning':''} title={t.incident?'Assigned':t.returning>0?`Returning · ${Math.ceil(t.returning)}s`:'Ready'}>{t.incident?'Working':t.returning>0?`${Math.ceil(t.returning)}s`:'Ready'}</i>)}</span>)}</div><output className="command-log" aria-live="polite"><Radio size={15}/><span>{state.log[0]?.text}</span></output></footer>
  </>}
 </DialogContent></Dialog>;
}
