import {insideWest,WEST_FOOTPRINT} from './west-layout';
import * as T from 'three';
import { residenceExterior } from './architecture';
import { loadResidenceModel, disposeResidence } from './residence-model';
import { buildOvalOffice } from './oval-office';
import { FollowCamera } from './follow-camera';
import {CameraObstacles,RenderBudget} from './render-budget';
import {gardenTree,gardenFinishes,westWingFinishes} from './landscape';
import {StaffModels,type StaffActor} from './npc-model';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import { Sky } from 'three/addons/objects/Sky.js';
import { loadPlayerModel, playerModelUrl, type PlayerModel, type Emote, type Locomotion } from './player-model';
import { destinations, npcs, floors, type Place, type NPC, type Destination } from './world-data';
import { material as mat, clearVisualResources, detailedFlag, deskDetails, carpetDetail, roomDetails, groundsDetails, lamp } from './visuals';

type Obstacle={x:number;z:number;w:number;d:number;height?:number};
type Hotspot={id:string;label:string;kind:'npc'|'door';x:number;z:number;target?:string;zone?:Place;spawn?:[number,number]};
export type GameState={location:string;zone:Place;x:number;z:number;heading:number;nearby:Hotspot|null;visited:string[];met:string[]};
type World={cameraObstacles?:CameraObstacles;group:T.Group;solids:Obstacle[];spots:Hotspot[];actors:{group:T.Group;data:NPC;staff?:StaffActor;loading?:Promise<void>}[];rings:T.Mesh[]};
const C={white:0xf5f0df,trim:0xe0dccb,window:0x355466,grass:0x718e43,path:0xcac8b0,gold:0xd9b458,wood:0x69412d,navy:0x192840};
function box(g:T.Group,x:number,y:number,z:number,w:number,h:number,d:number,color:number){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function cyl(g:T.Group,x:number,y:number,z:number,r:number,h:number,color:number,segments=12,top=r){const m=new T.Mesh(new T.CylinderGeometry(top,r,h,segments),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function ball(g:T.Group,x:number,y:number,z:number,r:number,color:number,detail=0){const m=new T.Mesh(new T.IcosahedronGeometry(r,detail),mat(color));m.position.set(x,y,z);m.castShadow=true;g.add(m);return m;}
function label(g:T.Group,text:string,x:number,y:number,z:number,size=3){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#142f32dd';ctx.beginPath();ctx.roundRect(3,3,506,88,15);ctx.fill();ctx.strokeStyle='#cbbb7c99';ctx.lineWidth=2;ctx.stroke();ctx.font='500 29px Arial';ctx.fillStyle='#f6ecd1';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,47,476);const tx=new T.CanvasTexture(canvas);tx.colorSpace=T.SRGBColorSpace;const s=new T.Sprite(new T.SpriteMaterial({map:tx,depthTest:true}));s.position.set(x,y,z);s.scale.set(size,size*96/512,1);g.add(s);return s;}
function mergeStatic(g:T.Group){
 g.updateMatrixWorld(true);const batches=new Map<string,{material:T.Material;geos:T.BufferGeometry[];cameraBlocker:boolean}>(),meshes:T.Mesh[]=[];const inverse=g.matrixWorld.clone().invert();
 g.traverse(child=>{if(child instanceof T.Mesh&&!child.userData.dynamic)meshes.push(child);});
 for(const child of meshes){const geo=child.geometry.index?child.geometry.toNonIndexed():child.geometry.clone();geo.applyMatrix4(inverse.clone().multiply(child.matrixWorld));const material=child.material as T.Material,cameraBlocker=!!child.userData.cameraBlocker,key=material.uuid+':'+cameraBlocker;const batch=batches.get(key)||{material,geos:[],cameraBlocker};batch.geos.push(geo);batches.set(key,batch);child.parent?.remove(child);child.geometry.dispose();}
 for(const {material,geos,cameraBlocker}of batches.values()){const merged=mergeGeometries(geos,false);geos.forEach(geo=>geo.dispose());if(!merged)throw new Error('Unable to assemble world geometry');const m=new T.Mesh(merged,material);m.castShadow=true;m.receiveShadow=true;m.userData.cameraBlocker=cameraBlocker;g.add(m);}
}
function solid(w:World,x:number,z:number,width:number,depth:number,height?:number){w.solids.push({x,z,w:width,d:depth,height});}
function tree(w:World,x:number,z:number,seed:number){gardenTree(w.group,x,z,seed);solid(w,x,z,.9,.9);}
function flowers(g:T.Group,x:number,z:number,w:number,d:number){box(g,x,.14,z,w,.28,d,0x3e5634);for(let i=0;i<Math.floor(w*d*1.3);i++){const px=x-w/2+((i*1.37)%w),pz=z-d/2+((i*.73)%d),h=.55+(i%3)*.09;cyl(g,px,h/2,pz,.02,h,0x526d37,4);for(let leaf=0;leaf<2;leaf++){const l=ball(g,px+(leaf?-.06:.06),h*.65,pz,.13,0x608343);l.scale.set(1,.22,.5);l.rotation.z=leaf?.5:-.5;}for(let petal=0;petal<5;petal++){const a=petal*Math.PI*2/5,b=ball(g,px+Math.cos(a)*.11,h,pz+Math.sin(a)*.11,.105,[0xefedcf,0xcc7379,0xf1bc9c,0xfff1e2][i%4]);b.scale.y=.5;}ball(g,px,h+.045,pz,.055,0xe7bf59);}}
function bench(g:T.Group,x:number,z:number,rot=0){const b=new T.Group();box(b,0,.6,0,2,.16,.65,0x6c6550);box(b,0,1.05,.3,2,.65,.14,0x6c6550);for(const sx of [-.8,.8]){box(b,sx,.3,0,.14,.6,.55,0x344846);}b.position.set(x,0,z);b.rotation.y=rot;g.add(b);}
function flag(g:T.Group,x:number,y:number,z:number,scale=1,presidential=false){detailedFlag(g,x,y,z,scale,presidential);}
function fountain(w:World,x:number,z:number,r:number){const g=w.group;cyl(g,x,.25,z,r,.5,0xb3b6a3,48);cyl(g,x,.53,z,r-.4,.12,0x71b2bb,48);const rim=new T.Mesh(new T.TorusGeometry(r-.15,.25,6,48),mat(0xe2dfc9));rim.rotation.x=Math.PI/2;rim.position.set(x,.56,z);g.add(rim);cyl(g,x,1.05,z,.75,1.6,0xc7c9b3,12,.4);cyl(g,x,1.85,z,1.7,.3,0xd7d8c2,24,1.9);cyl(g,x,2.75,z,.12,1.7,0x9ccbd2,8,.05);for(let i=0;i<10;i++){const a=i*Math.PI/5;const points=[];for(let j=0;j<=10;j++){const t=j/10;points.push(new T.Vector3(x+Math.cos(a)*t*(r-1),1.75+3*t-4.8*t*t,z+Math.sin(a)*t*(r-1)));}g.add(new T.Mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points),12,.04,4,false),mat(0xb5d8d5)));}solid(w,x,z,r*1.45,r*1.45);}
function ring(w:World,spot:Hotspot){w.spots.push(spot);const m=new T.Mesh(new T.TorusGeometry(1.0,.055,6,32),new T.MeshBasicMaterial({color:spot.kind==='npc'?0xe7cf8c:0x99dacf,transparent:true,opacity:.85}));m.rotation.x=Math.PI/2;m.position.set(spot.x,.10,spot.z);m.userData.dynamic=true;w.group.add(m);w.rings.push(m);if(spot.kind==='door'){label(w.group,spot.label,spot.x,3.2,spot.z,4.5);}}

export function grounds():World{const w:World={group:new T.Group(),solids:[],spots:[],actors:[],rings:[]},g=w.group;
 box(g,0,-.35,14,450,.6,450,0x6c8745);box(g,0,-.035,16,200,.06,225,0x547249);
 // One continuous lawn surface avoids mismatched repeating texture tiles.

 // Public-plan arrangement: north is -Z, east is +X. Gameplay dimensions are approximate.
 const ellipse=(cx:number,cz:number,rx:number,rz:number,width:number)=>{const shape=new T.Shape();shape.absellipse(cx,cz,rx,rz,0,Math.PI*2,false,0);const hole=new T.Path();hole.absellipse(cx,cz,rx-width,rz-width,0,Math.PI*2,true,0);shape.holes.push(hole);const m=new T.Mesh(new T.ShapeGeometry(shape,80),mat(C.path));m.rotation.x=Math.PI/2;m.position.y=.04; // Shape Y becomes world Z.
 m.material.side=T.DoubleSide;g.add(m);};ellipse(0,56,61,46,5);ellipse(0,-63,38,22,5);
 box(g,0,.03,15,11,.04,45,C.path);box(g,0,.025,-48,10,.05,24,C.path);box(g,0,.025,112,8,.05,24,C.path);box(g,-86,.025,16,5,.05,175,C.path);box(g,88,.025,16,5,.05,175,C.path);box(g,0,.025,-88,173,.05,5,C.path);box(g,0,.025,111,172,.05,5,C.path);box(g,-58,.025,19,44,.05,6,C.path);box(g,56,.025,24,56,.05,5,C.path);
 const fallback=new T.Group();fallback.name='Residence loading fallback';residenceExterior(fallback);fallback.traverse(o=>{o.userData.dynamic=true;});g.add(fallback);
 // Ground-level footprint of the imported residence, measured from its mesh.
 solid(w,0,-27.2,50,25.7);solid(w,0,-11.3,11.5,7.7);
 for(const side of [-1,1])solid(w,side*8,-9,6.2,12);
 solid(w,0,-46.3,16,13);for(const side of [-1,1])solid(w,side*11,-47,3.9,15.3);
 for(const side of [-1,1]){box(g,side*34,3.4,-27,18,.4,5.5,C.white);for(let i=0;i<7;i++)cyl(g,side*(26+i*2.7),1.65,-24.5,.22,3.3,C.white,8);}
 box(g,-58,3.4,-20,32,6.8,36,C.white);solid(w,-58,-20,32,36);box(g,-58,7,-20,33,.5,37,C.trim);for(let x=-71;x<-43;x+=4)for(const z of [-38.1,-1.9])box(g,x,2.55,z,1.8,2.45,.15,C.window);box(g,-41.9,1.8,-24,.15,3.5,2.5,C.window);
 const ov=cyl(g,-47,2.6,-1.5,6.8,5.2,C.white,24);ov.scale.z=.8;solid(w,-47,-1.5,11,9);for(let i=0;i<6;i++){const a=i/6*Math.PI;box(g,-47+Math.cos(a)*6.2,2.8,-1.5+Math.sin(a)*5.3,.8,2.8,.25,C.window);}
 box(g,-34,2.1,-31,18,4.2,7.5,C.white);solid(w,-34,-31,18,7.5);box(g,-34,4.35,-31,18.5,.3,8,C.trim);for(let x=-40;x<-26;x+=3){box(g,x,2.35,-27.18,1.5,2.25,.12,C.window);box(g,x,3.58,-27.1,1.8,.14,.24,C.white);}
 flag(g,0,18.53,-23,1.2);
 // Gardens and trees.
 for(const side of [-1,1]){const x=side===-1?-32:35,z=side===-1?10:18;box(g,x,.03,z,25,.08,18,0xb7b99b);box(g,x,.09,z,18,.1,12,0x698644);flowers(g,x,z-7,23,1.4);flowers(g,x,z+7,23,1.4);flowers(g,x-11,z,1.5,11);flowers(g,x+11,z,1.5,11);box(g,x,.15,z,3,.08,14,C.path);bench(g,x-7,z,Math.PI/2);bench(g,x+7,z,-Math.PI/2);}
 for(let i=0;i<28;i++){const z=-80+i*7.2;tree(w,-96+(i%3)*3,z,i);tree(w,95-(i%3)*3,z,i+30);}for(let i=0;i<16;i++){const x=-77+i*10;tree(w,x,-92,i+70);if(Math.abs(x)>22)tree(w,x,122,i+100);}for(const [x,z,s]of [[-62,78,34],[65,80,37],[-38,97,23],[38,95,18],[-54,43,16],[57,48,17],[-43,-63,2],[46,-67,5]])tree(w,x,z,s);
 fountain(w,0,48,5.5);fountain(w,0,-63,5);
 // Pool, putting green, benches and garden path details.
 box(g,-72,.02,50,19,.1,30,C.path);box(g,-72,.09,50,12,.1,24,0x54aeb7);for(let i=0;i<6;i++)box(g,-72,.15,42+i*3.5,10,.01,.08,0xb3e1d7);for(let i=0;i<4;i++)bench(g,-81,40+i*6,Math.PI/2);cyl(g,-53,.07,66,8,.1,0x5f883c,28);cyl(g,-53,.12,66,.25,.08,0x263924);flag(g,-53,.1,66,.45);
 for(let i=0;i<8;i++){const a=i/8*Math.PI*2,x=Math.cos(a)*65,z=56+Math.sin(a)*49;bench(g,x,z,-a+Math.PI/2);}
 for(let i=0;i<48;i++){const x=-98+i*4.1;for(const z of [-97,128]){box(g,x,1.05,z,.13,2.1,.13,0x2e4140);}box(g,x,1.6,-97,4.1,.09,.1,0x2e4140);box(g,x,1.6,128,4.1,.09,.1,0x2e4140);}for(let i=0;i<55;i++){for(const x of [-100,100]){const z=-97+i*4.1;box(g,x,1.05,z,.13,2.1,.13,0x2e4140);box(g,x,1.6,z,.1,.09,4.1,0x2e4140);}}
 // Ballroom construction, based on the published East Wing location.
 box(g,61,.03,-17,42,.12,48,0xaf9771);box(g,62,.13,-21,34,.24,34,0xc9c6b6);
 for(const x of [46,54,62,70,78])for(const z of [-37,-21,-5]){box(g,x,5.1,z,.38,10,.38,0x5f6965);solid(w,x,z,.48,.48);box(g,x,10.2,-21,.4,.45,33,0x586562);}
 for(const z of [-37,-21,-5]){box(g,62,10.2,z,33,.4,.4,0x61706a);box(g,62,6,z,33,.3,.3,0x64716c);}
 for(let i=0;i<4;i++){box(g,46+i*8,10.25,-13,.26,.26,16,0x89928a);box(g,46+i*8,10.25,-29,.26,.26,16,0x89928a);}
 const crane=new T.Group();crane.position.set(83,0,-32);for(const x of [-.7,.7])for(const z of [-.7,.7])box(crane,x,16,z,.22,32,.22,0xc79532);for(let y=1;y<32;y+=2){box(crane,0,y,-.7,1.6,.15,.15,0xe0aa37);box(crane,0,y,.7,1.6,.15,.15,0xe0aa37);const a=box(crane,0,y+.8,-.7,1.8,.12,.12,0xd8a538);a.rotation.z=.85;}box(crane,-8,31.3,0,32,.4,1.4,0xe4b548);box(crane,4,30.2,0,4,2.1,2.7,0x56676a);box(crane,-2,30,0,2,1.8,1.7,0xc8952f);box(crane,-2,30.2,-.9,1.65,1.1,.1,0x456473);cyl(crane,-16,22,0,.04,18,0x4d514b,6);box(crane,-16,13,0,1,.35,1,0xc2a253);g.add(crane);solid(w,83,-32,2,2);
 for(let i=0;i<5;i++){box(g,73,.35+i*.36,3,8,.3,1.7,0x8b7653);}for(let i=0;i<6;i++){cyl(g,43+i*6,.6,9,.35,1.1,0xe28e38,6,.08);box(g,43+i*6,.1,9,.75,.14,.75,0x4c4f43);}
 const digger=new T.Group();digger.position.set(69,0,-47);box(digger,0,.5,0,3,1,4,0x414a45);box(digger,0,1.4,0,2.6,1,3,0xe3ac3e);box(digger,0,2.7,-.5,2,1.7,1.7,0xe2b044);box(digger,0,2.9,-1.39,1.7,1.1,.06,0x3e5c60);const arm=box(digger,0,3.5,2,.5,.5,4,0xe1a437);arm.rotation.x=.5;box(digger,0,1.4,4.5,2,.5,1.5,0x7d7250);g.add(digger);solid(w,69,-47,3,5);
 label(g,'BALLROOM · UNDER CONSTRUCTION',59,3.2,10,7);
 ring(w,{id:'south-door',label:'Enter the residence',kind:'door',x:0,z:-4.7,target:'diplomatic'});ring(w,{id:'north-door',label:'Enter the Entrance Hall',kind:'door',x:0,z:-55,target:'entrance'});ring(w,{id:'west-door',label:'Enter the West Wing',kind:'door',x:-39,z:-23,zone:'west',spawn:[40,-21]});ring(w,{id:'west-front',label:'West Wing north entrance',kind:'door',x:-60,z:-40,zone:'west',spawn:[-5.5,-18]});
 groundsDetails(g);gardenFinishes(g);westWingFinishes(g);for(const x of [-62.8,-57.2])solid(w,x,-41.55,.7,.7,4.6);for(const [x,z]of [[-32,10],[35,18]])for(const dx of [-9,9])for(const dz of [-5.5,5.5])solid(w,x+dx,z+dz,1.1,1.1,1.7);const sky=new Sky();sky.scale.setScalar(10000);sky.userData.dynamic=true;sky.frustumCulled=false;sky.material.uniforms.turbidity.value=3.2;sky.material.uniforms.rayleigh.value=1.5;sky.material.uniforms.mieCoefficient.value=.004;sky.material.uniforms.mieDirectionalG.value=.8;sky.material.uniforms.sunPosition.value.set(-35,60,28);g.add(sky);mergeStatic(g);return w;
}

export class Game{
 residence:T.Group|null=null;
 followCamera=new FollowCamera();
 budget=new RenderBudget(Math.min(typeof window!=='undefined'&&window.matchMedia?.('(pointer: coarse)').matches?1:1.5,window.devicePixelRatio||1));
 shadowTick=0;staffModels=new StaffModels();staffEnabled=false;
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(48,1,.1,420);player=new T.Group();playerModel:PlayerModel|null=null;worlds=new Map<Place,World>();world:World;zone:Place='grounds';keys=new Set<string>();yaw=0;pitch=.25;velocityY=0;paused=false;disposed=false;nearby:Hotspot|null=null;visited=new Set<string>();met=new Set<string>();last=0;frame=0;tick=0;walkTime=0;audio:T.AudioListener|null=null;audioContext:AudioContext|null=null;ambient:AudioBufferSourceNode|null=null;gain:GainNode|null=null;cleanup:(()=>void)[]=[];sun=new T.DirectionalLight(0xfff4e4,2.15);hemi=new T.HemisphereLight(0xd9e9fa,0x77836b,1.85);
 constructor(public mount:HTMLElement,public update:(s:GameState)=>void,public talk:(id:string)=>void,public map:()=>void){this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(this.budget.ratio);this.renderer.shadowMap.autoUpdate=false;this.renderer.shadowMap.needsUpdate=true;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.02;this.renderer.domElement.tabIndex=0;this.renderer.domElement.setAttribute('aria-label','Game view. WASD or arrows to move; drag to look; E to interact.');mount.appendChild(this.renderer.domElement);this.scene.background=new T.Color(0xa4cee0);this.scene.fog=new T.Fog(0xa4cee0,140,360);this.scene.add(this.hemi);this.sun.position.set(-55,85,45);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-42,right:42,top:42,bottom:-42,near:1,far:250});this.sun.shadow.bias=-.0007;this.sun.shadow.normalBias=.045;this.scene.add(this.sun);this.scene.add(this.sun.target);this.world=grounds();this.worlds.set('grounds',this.world);this.addNPCs(this.world,'grounds');this.scene.add(this.world.group);this.player.position.set(0,0,38);this.scene.add(this.player);this.camera.position.set(0,5.2,49);this.camera.lookAt(0,2,22);this.events();this.publish();this.frame=requestAnimationFrame(this.loop);}
 async loadPlayer(){const model=await loadPlayerModel(playerModelUrl(window.location.pathname));if(this.disposed){model.dispose();return;}this.playerModel=model;this.player.add(model.object);}
 async loadArchitecture(){const model=await loadResidenceModel(window.location.pathname);if(this.disposed){disposeResidence(model);return;}const grounds=this.worlds.get('grounds')!,fallback=grounds.group.getObjectByName('Residence loading fallback');if(fallback){grounds.group.remove(fallback);fallback.traverse(o=>{if(o instanceof T.Mesh)o.geometry.dispose();});}this.residence=model;grounds.group.add(model);this.renderer.shadowMap.needsUpdate=true;}
 events(){const canvas=this.renderer.domElement;const listen=(el:EventTarget,type:string,fn:EventListener,options?:AddEventListenerOptions)=>{el.addEventListener(type,fn,options);this.cleanup.push(()=>el.removeEventListener(type,fn,options));};
 listen(window,'keydown',((e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(target.matches('input,textarea,select')||target.isContentEditable||target.closest('[role=dialog]')||(e.code==='Space'&&target.tagName==='BUTTON'))return;if(e.code==='KeyM'&&!e.repeat){e.preventDefault();this.map();return;}if(this.paused)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)this.interact();if(e.code==='Space'&&!e.repeat)this.jump();if(!e.repeat){const moves:Record<string,Emote>={KeyG:'dance',KeyY:'ymca',KeyV:'victory',KeyB:'backflip'};if(moves[e.code])this.emote(moves[e.code]);if(e.code==='Escape')this.emote(null);}}) as EventListener);
 listen(window,'keyup',((e:KeyboardEvent)=>{this.keys.delete(e.code);}) as EventListener);listen(window,'blur',()=>this.keys.clear());listen(document,'visibilitychange',()=>{this.keys.clear();if(document.hidden)void this.audioContext?.suspend();else if(this.gain&&this.gain.gain.value>0)void this.audioContext?.resume();});
 let dragging=false,px=0,py=0;listen(canvas,'pointerdown',((e:PointerEvent)=>{if(this.paused)return;dragging=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.focus();}) as EventListener);listen(canvas,'pointermove',((e:PointerEvent)=>{if(!dragging||this.paused)return;this.yaw+=(e.clientX-px)*.006;this.pitch=T.MathUtils.clamp(this.pitch+(e.clientY-py)*.003,-.08,.95);px=e.clientX;py=e.clientY;}) as EventListener);for(const type of ['pointerup','pointercancel','lostpointercapture'])listen(canvas,type,()=>{dragging=false;});listen(canvas,'contextmenu',e=>e.preventDefault());const resize=()=>{this.camera.aspect=this.mount.clientWidth/this.mount.clientHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(this.mount.clientWidth,this.mount.clientHeight);};const ro=new ResizeObserver(resize);ro.observe(this.mount);this.cleanup.push(()=>ro.disconnect());resize();
 }
 addNPCs(w:World,zone:Place){for(const data of npcs.filter(n=>n.zone===zone)){const actor=new T.Group();actor.name=data.name;actor.position.set(data.x,0,data.z);w.group.add(actor);const tag=label(actor,data.name,0,3.35,0,2.4);tag.userData.npcLabel=true;w.actors.push({group:actor,data});ring(w,{id:data.id,label:data.name,kind:'npc',x:data.x,z:data.z});}}
 async loadStaff(){this.staffEnabled=true;const w=this.world;await Promise.all(w.actors.map(actor=>{if(actor.staff)return Promise.resolve();if(actor.loading)return actor.loading;actor.loading=this.staffModels.create(window.location.pathname,actor.data.id).then(model=>{if(!model)return;actor.staff=model;actor.group.add(model.object);this.renderer.shadowMap.needsUpdate=true;}).finally(()=>{actor.loading=undefined;});return actor.loading;}));}
 emote(name:Emote|null){if(this.player.position.y<=.01){this.keys.clear();this.playerModel?.emote(name);}}
 key(code:string,on:boolean){if(on&&!this.paused)this.keys.add(code);else this.keys.delete(code);}
 focus(){this.renderer.domElement.focus();}
 pause(value:boolean){this.paused=value;this.keys.clear();}
 jump(){if(!this.paused&&this.player.position.y<=.01){this.playerModel?.emote(null);this.velocityY=6.5;}}
 blocked(x:number,z:number){if(this.zone==='grounds'&&(x<-98||x>98||z<-95||z>126))return true;if(this.zone==='west'&&!insideWest(x,z))return true;if(this.zone!=='grounds'&&this.zone!=='west'&&(x<-28.7||x>28.7||z<-18.7||z>18.7))return true;return this.world.solids.some(o=>Math.abs(x-o.x)<o.w/2+.36&&Math.abs(z-o.z)<o.d/2+.36);}
 travel(id:string){const d=destinations.find(d=>d.id===id);if(!d)throw new Error('Unknown destination');this.change(d.zone,d.spawn?.[0]??d.x,d.spawn?.[1]??(d.room?(d.z>2?d.z-d.room.d/2+1.6:d.z<-2?d.z+d.room.d/2-1.6:d.z):d.z));this.visited.add(id);this.publish();}
 change(zone:Place,x:number,z:number){this.renderer.shadowMap.needsUpdate=true;this.playerModel?.emote(null);if(zone!==this.zone){this.scene.remove(this.world.group);if(!this.worlds.has(zone)){const w=interior(zone);this.addNPCs(w,zone);this.worlds.set(zone,w);}this.zone=zone;this.world=this.worlds.get(zone)!;this.scene.add(this.world.group);}if(this.staffEnabled)void this.loadStaff().catch(error=>console.warn('Staff could not load; re-enter the room to retry.',error));this.player.position.set(x,0,z);this.player.visible=true;this.followCamera.reset();this.camera.fov=zone==='grounds'?52:66;this.camera.updateProjectionMatrix();this.yaw=0;this.pitch=.32;this.velocityY=0;this.keys.clear();this.nearby=null;this.scene.background=new T.Color(zone==='grounds'?0xa4cee0:0xabb9b7);this.scene.fog=zone==='grounds'?new T.Fog(0xa4cee0,140,360):null;this.hemi.intensity=zone==='grounds'?1.85:1.7;this.hemi.groundColor.setHex(zone==='grounds'?0x596142:0x817158);this.sun.intensity=zone==='grounds'?2.15:1.8;this.camera.position.set(x,5,z+9);this.publish();}
 interact(){if(this.paused||!this.nearby)return;const n=this.nearby;if(n.kind==='npc'){this.keys.clear();this.met.add(n.id);this.publish();this.talk(n.id);}else if(n.target)this.travel(n.target);else if(n.zone&&n.spawn)this.change(n.zone,...n.spawn);}
 publish(){const p=this.player.position;let location=this.zone==='grounds'?'White House grounds':this.zone==='west'?'West Wing corridor':'Residence corridor';for(const d of destinations.filter(d=>d.zone===this.zone)){const inRoom=d.room?Math.abs(p.x-d.x)<d.room.w/2&&Math.abs(p.z-d.z)<d.room.d/2:Math.hypot(p.x-d.x,p.z-d.z)<(d.id==='south'?30:d.id==='north'?30:14);if(inRoom){location=d.name;this.visited.add(d.id);break;}}this.update({location,zone:this.zone,x:p.x,z:p.z,heading:this.yaw,nearby:this.nearby,visited:[...this.visited],met:[...this.met]});}
 loop=(now:number)=>{if(this.disposed)return;if(document.hidden){this.last=now;this.frame=requestAnimationFrame(this.loop);return;}const elapsed=(now-(this.last||now))/1000,dt=Math.min(elapsed,.04);this.last=now;if(this.budget.sample(elapsed))this.renderer.setPixelRatio(this.budget.ratio);const p=this.player.position;const previousX=p.x,previousZ=p.z;const running=this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'),slow=this.keys.has('KeyC');const mode:Locomotion=running?(slow?'sprint':'run'):(slow?'stroll':'walk');if(!this.paused){if(this.keys.has('KeyQ'))this.yaw-=dt*1.8;if(this.keys.has('KeyR'))this.yaw+=dt*1.8;let forward=(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)-(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0),right=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0);const len=Math.hypot(forward,right);if(len){forward/=len;right/=len;const speed=({walk:3.2,stroll:1.6,run:6.5,sprint:9}[mode])*(this.zone==='grounds'?1:.78);const dx=(Math.sin(this.yaw)*forward+Math.cos(this.yaw)*right)*speed*dt,dz=(-Math.cos(this.yaw)*forward+Math.sin(this.yaw)*right)*speed*dt;if(!this.blocked(p.x+dx,p.z))p.x+=dx;if(!this.blocked(p.x,p.z+dz))p.z+=dz;const target=-Math.atan2(dx,-dz);this.player.rotation.y+=Math.atan2(Math.sin(target-this.player.rotation.y),Math.cos(target-this.player.rotation.y))*Math.min(1,dt*13);this.walkTime+=dt*speed*1.8;}this.velocityY-=dt*17;p.y=Math.max(0,p.y+this.velocityY*dt);if(p.y===0)this.velocityY=0;
 let near:Hotspot|null=null,best=3.5;for(const spot of this.world.spots){const distance=Math.hypot(p.x-spot.x,p.z-spot.z);if(distance<best){near=spot;best=distance;}}this.nearby=near;for(const a of this.world.actors){const distance=a.group.position.distanceTo(p);if(distance<7){const target=-Math.atan2(p.x-a.group.position.x,-(p.z-a.group.position.z));a.group.rotation.y+=Math.atan2(Math.sin(target-a.group.rotation.y),Math.cos(target-a.group.rotation.y))*Math.min(1,dt*3);}a.group.visible=distance<65;if(distance<24)a.staff?.animate(dt);a.group.position.y=0;}}
 if(!this.paused)this.playerModel?.animate(Math.hypot(p.x-previousX,p.z-previousZ),dt,p.y>.01,mode);
 const indoors=this.zone!=='grounds',distance=indoors?5.4:8.2,pitch=indoors?Math.max(.08,this.pitch):this.pitch;const target=new T.Vector3(p.x,p.y+2.15,p.z);const desired=target.clone().add(new T.Vector3(-Math.sin(this.yaw)*distance*Math.cos(pitch),Math.sin(pitch)*distance,Math.cos(this.yaw)*distance*Math.cos(pitch)));
 const oval=destinations.find(d=>d.id==='oval')!;const inOval=this.zone==='west'&&((p.x-oval.x)/8)**2+((p.z-oval.z)/8.6)**2<1.03;
 // In the Oval Office only architectural surfaces push the camera: flags and chair backs cannot whip it into the avatar.
 // Broad-phase footprints keep camera collision independent of render-mesh detail.
 this.world.cameraObstacles??=new CameraObstacles(this.world.solids,this.zone==='grounds');
 const surfaces=this.world.cameraObstacles.nearby(p.x,p.z,inOval);
 const follow=this.followCamera.solve(target,desired,surfaces,dt);this.camera.position.copy(follow.position);this.player.visible=follow.showPlayer;this.camera.lookAt(target);
 for(const r of this.world.rings){(r.material as T.MeshBasicMaterial).opacity=.55+Math.sin(now*.003)*.2;}this.tick+=dt;if(this.tick>.20){this.publish();this.tick=0;}this.shadowTick+=elapsed; if(this.shadowTick>1/15){this.shadowTick=0;this.sun.position.set(p.x-35,60,p.z+28);this.sun.target.position.set(p.x,0,p.z);this.renderer.shadowMap.needsUpdate=true;}for(const object of this.world.group.children){if(object.userData.distanceCull){const d=object.position.distanceTo(p);object.visible=d<object.userData.distanceCull;for(const part of object.children){if(part.userData.leafDetail){part.visible=!!this.world.group.userData.foliageReady;if(part instanceof T.InstancedMesh)part.count=d<45?96:d<90?64:48;}if(part.userData.foliageCore)part.visible=!this.world.group.userData.foliageReady;}}}this.camera.updateMatrixWorld();for(const actor of this.world.actors)for(const child of actor.group.children)if(child instanceof T.Sprite){const distance=actor.group.position.distanceTo(p);child.visible=this.mount.clientWidth>700&&!window.matchMedia?.('(pointer: coarse)').matches&&distance>4&&distance<12;if(child.visible){const depth=Math.max(.1,child.getWorldPosition(new T.Vector3()).applyMatrix4(this.camera.matrixWorldInverse).z*-1);const worldWidth=150/this.mount.clientHeight*2*depth*Math.tan(T.MathUtils.degToRad(this.camera.fov/2));child.scale.set(Math.min(2.4,worldWidth),Math.min(2.4,worldWidth)*96/512,1);}}this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(this.loop);};
 sound(enabled:boolean){if(!this.audioContext&&enabled){this.audioContext=new AudioContext();const ctx=this.audioContext,buffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate);const samples=buffer.getChannelData(0);let brown=0;for(let i=0;i<samples.length;i++){brown=(brown+Math.random()*.02-.01)/1.02;samples[i]=brown*.8;}this.ambient=ctx.createBufferSource();this.ambient.buffer=buffer;this.ambient.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=600;this.gain=ctx.createGain();this.gain.gain.value=0;this.ambient.connect(filter);filter.connect(this.gain);this.gain.connect(ctx.destination);this.ambient.start();}if(this.audioContext&&this.gain){void this.audioContext.resume();this.gain.gain.setTargetAtTime(enabled?.4:0,this.audioContext.currentTime,.4);}}
 dispose(){if(this.residence){this.residence.parent?.remove(this.residence);disposeResidence(this.residence);this.residence=null;}this.disposed=true;cancelAnimationFrame(this.frame);this.cleanup.forEach(fn=>fn());void this.audioContext?.close();if(this.playerModel){this.player.remove(this.playerModel.object);this.playerModel.dispose();this.playerModel=null;}const geos=new Set<T.BufferGeometry>(),mats=new Set<T.Material>(),textures=new Set<T.Texture>();const collect=(obj:T.Object3D)=>{obj.traverse(child=>{if(child instanceof T.Mesh||child instanceof T.Sprite){if(child instanceof T.Mesh)geos.add(child.geometry);if(child instanceof T.InstancedMesh)child.dispose();for(const m of Array.isArray(child.material)?child.material:[child.material]){mats.add(m);if('map'in m&&m.map instanceof T.Texture)textures.add(m.map);}}});};this.worlds.forEach(w=>{for(const actor of w.actors)if(actor.staff){actor.group.remove(actor.staff.object);actor.staff.dispose();}w.cameraObstacles?.dispose();collect(w.group);});this.staffModels.dispose();collect(this.player);geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());clearVisualResources();this.renderer.dispose();this.renderer.domElement.remove();}
}

function chair(g:T.Group,x:number,z:number,color:number,rotation=0){const c=new T.Group();box(c,0,.61,0,.87,.18,.90,C.wood);cushion(c,0,.75,-.015,.76,.16,.79,color);box(c,0,1.18,.4,.88,1.05,.18,C.wood);cushion(c,0,1.19,.28,.73,.88,.15,color);for(const sx of [-.31,.31])for(const sz of [-.3,.3]){cyl(c,sx,.30,sz,.052,.61,C.wood,8,.065);}for(const side of [-1,1]){box(c,side*.48,.98,.05,.12,.13,.78,C.wood);cyl(c,side*.48,.78,-.24,.04,.4,C.wood,8);}for(const sx of [-.19,.19])for(const sy of [1.0,1.36]){const button=ball(c,sx,sy,.19,.024,C.gold);button.scale.z=.5;}c.position.set(x,0,z);c.rotation.y=rotation;g.add(c);}
function desk(w:World,x:number,z:number,width=4,depth=1.7){const g=w.group;box(g,x,1.14,z,width,.27,depth,C.wood);box(g,x,1.26,z,width+.1,.08,depth+.1,0x815434);for(const side of [-1,1]){box(g,x+side*(width/2-.55),.52,z,1.02,1.1,depth-.15,0x6b452b);for(let j=0;j<3;j++){box(g,x+side*(width/2-.55),.3+j*.3,z-depth/2,.85,.23,.04,0x845d3c);box(g,x+side*(width/2-.55),.3+j*.3,z-depth/2-.04,.18,.035,.025,C.gold);}}box(g,x,1.32,z-.13,.75,.025,.55,0xf3eddb);box(g,x+.8,1.35,z,.5,.1,.4,0x1e2d32);deskDetails(g,x,z,width,depth,width>=4.7);solid(w,x,z,width,depth);}
function cushion(g:T.Group,x:number,y:number,z:number,w:number,h:number,d:number,color:number){const m=new T.Mesh(new RoundedBoxGeometry(w,h,d,1,.065),mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function sofa(g:T.Group,x:number,z:number,rot=0,color=0xe0cf9e){const s=new T.Group();cushion(s,0,.55,0,2.6,.7,1,color);cushion(s,0,1.1,.44,2.6,1,.3,color);cushion(s,-1.25,.83,0,.28,.7,1.1,color);cushion(s,1.25,.83,0,.28,.7,1.1,color);for(const sx of [-.85,0,.85])cushion(s,sx,.97,-.05,.77,.15,.78,color);for(const sx of [-1,1])for(const sz of [-.35,.35])cyl(s,sx,.16,sz,.07,.32,C.wood,8);for(const sx of [-.85,0,.85])for(const sy of [1.08,1.38])ball(s,sx,sy,.255,.045,0xc4b182);s.position.set(x,0,z);s.rotation.y=rot;g.add(s);}
function plant(g:T.Group,x:number,y:number,z:number){cyl(g,x,y+.35,z,.35,.7,0xc5b392,10,.42);for(let i=0;i<5;i++){const leaf=ball(g,x+Math.sin(i*2)*.24,y+1.1+(i%2)*.25,z+Math.cos(i*2)*.23,.46,0x527348);leaf.scale.set(.7,1.5,.7);}}
function chandelier(g:T.Group,x:number,z:number){cyl(g,x,4.15,z,.055,1.2,C.gold,8);const ring=new T.Mesh(new T.TorusGeometry(.9,.06,6,12),mat(C.gold));ring.rotation.x=Math.PI/2;ring.position.set(x,3.8,z);g.add(ring);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;cyl(g,x+Math.cos(a)*.9,3.98,z+Math.sin(a)*.9,.08,.42,0xffefbd,6);ball(g,x+Math.cos(a)*.9,3.58,z+Math.sin(a)*.9,.12,0xe9e7cc);}}
function rug(g:T.Group,x:number,z:number,rx:number,rz:number,color:number,oval=false){carpetDetail(g,x,z,rx,rz,oval);if(oval){const r=cyl(g,x,.075,z,rx,.04,C.gold,48);r.scale.z=rz/rx;const r2=cyl(g,x,.105,z,rx-.15,.025,color,48);r2.scale.z=(rz-.15)/(rx-.15);}else{box(g,x,.075,z,rx*2,.03,rz*2,C.gold);box(g,x,.097,z,rx*2-.25,.025,rz*2-.25,color);}for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const star=ball(g,x+Math.cos(a)*rx*.78,.13,z+Math.sin(a)*rz*.78,.08,0xdfc985);star.scale.y=.1;}}
function wall(w:World,x:number,z:number,length:number,vertical:boolean,color:number,doors:number[]){const start=(vertical?z:x)-length/2,end=start+length;const openings=doors.filter(d=>d>start+1.2&&d<end-1.2).sort((a,b)=>a-b);const parts:{a:number;b:number}[]=[];let p=start;for(const d of openings){if(d-1.6>p)parts.push({a:p,b:d-1.6});p=Math.max(p,d+1.6);}if(p<end)parts.push({a:p,b:end});const g=w.group;for(const {a,b}of parts){const px=vertical?x:(a+b)/2,pz=vertical?(a+b)/2:z;box(g,px,2.3,pz,vertical?.22:b-a,4.6,vertical?b-a:.22,color);box(g,px,.6,pz,vertical?.27:b-a,1.2,vertical?b-a:.27,0xe9e2cd);box(g,px,1.25,pz,vertical?.3:b-a,.07,vertical?b-a:.3,C.gold);box(g,px,4.45,pz,vertical?.38:b-a,.2,vertical?b-a:.38,C.white);solid(w,px,pz,vertical?.22:b-a,vertical?b-a:.22);}for(const d of openings){box(g,vertical?x:d,4.1,vertical?d:z,vertical?.25:3.2,1,vertical?3.2:.25,color);for(const sign of [-1,1])box(g,vertical?x:d+sign*1.6,1.85,vertical?d+sign*1.6:z,vertical?.33:.11,3.7,vertical?.11:.33,C.white);}}
function furnish(w:World,d:Destination){const g=w.group,{x,z}=d,r=d.room!,{style}=r;const rx=r.w/2,rz=r.d/2;
 if(style==='oval'){w.solids.push(...buildOvalOffice(g,x,z));return;}
 // Parquet strips and wall molding preserve readable rooms with an open camera ceiling.
 for(let i=0;i<Math.floor(r.w);i++)box(g,x-rx+.5+i,.047,z,.95,.016,r.d-.25,i%2?0xb69b70:0xbea377);
 const north=z-rz,south=z+rz;roomDetails(g,d);
 wall(w,x,north,r.w,false,r.color,r.doors?r.doors.north??[]:[x]);wall(w,x,south,r.w,false,r.color,r.doors?r.doors.south??[]:[x]);wall(w,x-rx,z,r.d,true,r.color,r.doors?r.doors.west??[]:[-10,0,10]);wall(w,x+rx,z,r.d,true,r.color,r.doors?r.doors.east??[]:[-10,0,10]);
 label(g,d.name,x,3.7,z>0?north+.22:south-.22,Math.min(4.2,r.w*.62));
 if(style==='kitchen'||style==='flowers'||style==='press'||style==='games')for(const side of [-1,1]){const wx=x+side*(rx-1.5),wz=z+(z>=0?rz:-rz)*.985;box(g,wx,2.6,wz,1.4,2.5,.13,0x8aabb4);box(g,wx,2.6,wz-(z>=0?.11:-.11),.065,2.5,.18,C.white);box(g,wx,2.6,wz-(z>=0?.11:-.11),1.4,.07,.18,C.white);for(const sx of [-.87,.87])box(g,wx+sx,2.7,wz,.34,3.05,.25,0xbca171);}
 if(style==='corridor')return;
 if(style==='small-office'){desk(w,x,z+rz-1.8,Math.min(2.2,r.w-1.6),1);chair(g,x,z+rz-.7,0x4b3b2d);return;}
 if(style==='palm'){for(const px of [x-rx+1.4,x+rx-1.4])for(const pz of [z-rz+1.5,z+rz-1.5])plant(g,px,0,pz);bench(g,x,z-rz+1,0);return;}
 if(style==='press-offices'){for(let px=x-rx+4;px<x+rx-2;px+=5)for(const pz of [z-rz+3,z+rz-4]){desk(w,px,pz,2.6,1.2);chair(g,px,pz+1.2,0x394d57);}return;}
 chandelier(g,x,z);
 if(style==='office'){
   rug(g,x,z,rx*.7,rz*.6,0x61736d);desk(w,x,z+rz-3,Math.min(r.w-3,3.8));chair(g,x,z+rz-1.6,0x4b3b2d);lamp(g,x-1.25,1.32,z+rz-2.7);chair(g,x-1,z+1,0x716958);chair(g,x+1,z+1,0x716958);plant(g,x-rx+1.2,0,z+rz-1.4);flag(g,x+rx-1.2,0,z+rz-1.2,.53);
 }else if(style==='meeting'||style==='dining'){
   const length=Math.min(r.d-5,style==='dining'?12:7);rug(g,x,z,rx*.77,rz*.78,0x778177);box(g,x,1.2,z,3.2,.2,length,C.wood);for(const sz of [-length/2+1,length/2-1])box(g,x,.6,z+sz,1.9,1.2,.4,C.wood);solid(w,x,z,3.2,length);for(let i=0;i<Math.floor(length/1.7);i++)for(const side of [-1,1]){const cz=z-length/2+.9+i*1.7;chair(g,x+side*2.25,cz,0x584837,side>0?Math.PI/2:-Math.PI/2);box(g,x+side*.85,1.34,cz,.55,.02,.5,C.white);cyl(g,x+side*1.15,1.42,cz-.3,.08,.2,0xc5d0c2,8);}flag(g,x-rx+1.3,0,z+rz-1.3,.55);
 }else if(style==='press'){
   const podiumX=x+rx-3;box(g,podiumX,.13,z,3.5,.24,r.d-5,0x334b61);box(g,podiumX,.85,z,.9,1.5,.8,0x42536b);box(g,podiumX,1.65,z,1.3,.12,1,C.wood);box(g,x+rx-.4,2.4,z,.12,4,r.d-5,0x284f70);label(g,'THE WHITE HOUSE',x+rx-.6,2.8,z,3);solid(w,podiumX,z,1.3,1);for(let row=0;row<5;row++)for(const offset of [-4.5,-2.7,2.7,4.5]){const px=x-rx+3+row*3;chair(g,px,z+offset,0x315576,-Math.PI/2);solid(w,px,z+offset,.95,.95);}flag(g,podiumX,0,z+4,.55);
 }else if(style==='bedroom'){
   rug(g,x,z,rx*.7,rz*.65,0x7d7773);box(g,x,0.65,z+1,3.5,.75,4.4,C.wood);box(g,x,1.1,z+1,3.4,.25,4.2,0xf1e7cd);box(g,x,1.28,z+1.6,3.3,.16,2.6,0xa3afa0);box(g,x,1.8,z-1.2,3.6,1.8,.2,C.wood);for(const side of [-1,1]){box(g,x+side*.85,1.3,z-.5,1.2,.23,.8,C.white);cyl(g,x+side*1.75,1.5,z-1.2,.1,3,C.wood);desk(w,x+side*(rx-1.4),z-1,1.3,1.1);}solid(w,x,z+1,3.5,4.4);plant(g,x-rx+1.2,0,z+rz-1.3);
 }else if(style==='kitchen'){
   box(g,x,1,z,3.4,1.6,3.8,0xb8bfc0);box(g,x,1.88,z,3.6,.15,4,0xe2e5d8);solid(w,x,z,3.6,4);box(g,x-rx+1.3,1,z,1.8,1.8,r.d-4,0xd1d2c6);box(g,x-rx+1.3,2,z,2,.15,r.d-4,0x89989a);for(let i=0;i<4;i++)cyl(g,x-rx+1.3,2.12,z-rz+3+i*2,.4,.16,0x48545a,12);box(g,x+rx-1.1,1.8,z+rz-2,1.7,3.5,1.7,0xa8b5b6);solid(w,x-rx+1.3,z,2,r.d-4);
 }else if(style==='library'||style==='china'){
   for(const side of [-1,1]){box(g,x+side*(rx-.7),1.6,z,1.1,3.2,r.d-5,C.wood);for(let shelf=0;shelf<4;shelf++){box(g,x+side*(rx-.7),.55+shelf*.72,z,1.25,.1,r.d-5,0x94754e);for(let j=0;j<Math.floor(r.d-5);j++){if(style==='china'){const plate=cyl(g,x+side*(rx-.95),.85+shelf*.72,z-rz+3+j,.24,.06,C.white,12);plate.rotation.z=Math.PI/2;}else box(g,x+side*(rx-.78),.89+shelf*.72,z-rz+2.8+j,.7,.53,.5,[0x657262,0x8a5145,0x416174,0xbaa15d][(j+shelf)%4]);}}solid(w,x+side*(rx-.7),z,1.1,r.d-5);}rug(g,x,z,rx*.55,rz*.52,0x8c7660);cyl(g,x,.9,z,1.1,.15,C.wood);cyl(g,x,.45,z,.3,.9,C.wood);chair(g,x,z+2,0x8c6e54);
 }else if(style==='flowers'){
   desk(w,x,z+2,Math.min(5,r.w-4),1.8);for(let i=0;i<5;i++){const px=x-1.7+i*.85;cyl(g,px,1.55,z+2,.2,.5,0x7e9ca2,8,.25);for(let j=0;j<3;j++)ball(g,px+Math.sin(j*2)*.17,2.05,z+2+Math.cos(j*2)*.17,.23,[0xe4c3c3,0xe7ddb5,0xc9989e][j]);}for(const side of [-1,1])plant(g,x+side*(rx-1.5),0,z+rz-2);
 }else if(style==='games'){
   box(g,x,1,z,3.5,.3,6,C.wood);box(g,x,1.19,z,3.1,.1,5.6,0x477556);for(const sx of [-1,1])for(const sz of [-2,2])box(g,x+sx,.5,z+sz,.2,1,.2,C.wood);for(let i=0;i<7;i++)ball(g,x+Math.sin(i)*.75,1.33,z+Math.cos(i)*1.7,.12,[0xf4e9c9,0xc95240,0xd6aa32][i%3]);solid(w,x,z,3.5,6);sofa(g,x-rx+2,z,Math.PI/2);
 }else if(style==='music'){
   box(g,x,1.2,z,3,.5,3.5,0x272c2c);box(g,x,1.45,z-1.5,2.7,.1,.7,C.white);for(let i=0;i<14;i++)box(g,x-1.2+i*.18,1.54,z-1.4,.08,.06,.25,0x1a2525);const lid=box(g,x,2,z+.3,3,.1,2.8,0x272c2c);lid.rotation.z=.2;for(const sx of [-1.2,1.2])box(g,x+sx,.6,z+1,.15,1.2,.15,0x272c2c);chair(g,x,z-2.5,0x4d4037,Math.PI);solid(w,x,z,3,3.5);
 }else if(style==='ballroom'){
   for(const sz of [-10,0,10]){chandelier(g,x,z+sz);rug(g,x,z+sz,rx*.67,3.2,0xc8b890);sofa(g,x-rx+1.3,z+sz,Math.PI/2,0xe8d8b0);}plant(g,x+rx-1.2,0,z-rz+2);plant(g,x+rx-1.2,0,z+rz-2);
 }else if(style==='hall'){
   for(const sx of [-11,11]){cyl(g,x+sx,2.1,z,.34,4.2,C.white,12);plant(g,x+sx,0,z+3.5);}rug(g,x,z,6,4,0xa24f48);
 }else{
   rug(g,x,z,rx*.71,rz*.62,style==='salon-oval'?0x41627a:0x867660,style==='salon-oval');cyl(g,x,.85,z,1.0,.15,C.wood);cyl(g,x,.42,z,.25,.85,C.wood);sofa(g,x-rx+1.6,z,Math.PI/2);sofa(g,x+rx-1.6,z,-Math.PI/2);plant(g,x-rx+1.1,0,z+rz-1.3);plant(g,x+rx-1.1,0,z+rz-1.3);
 }
}
export function interior(zone:Place):World {const w:World={group:new T.Group(),solids:[],spots:[],actors:[],rings:[]};const g=w.group;if(zone==='west'){for(const r of WEST_FOOTPRINT)box(g,r.x,-.15,r.z,r.w,.3,r.d,0xcfbf98);}else box(g,0,-.15,0,60,.3,40,0xcfbf98);for(let i=-28;i<29;i+=2)for(let j=-18;j<20;j+=2)if(zone!=='west')box(g,i,.018,j,1.99,.025,1.99,((i+j)/2)%2?0xcec8b3:0xe7e0c8);for(const d of destinations.filter(d=>d.zone===zone&&d.room))furnish(w,d);
 if(zone==='west'){ring(w,{id:'exit-west',label:'Exit to the Rose Garden',kind:'door',x:44,z:-18.5,zone:'grounds',spawn:[-38,-23]});ring(w,{id:'residence-west',label:'Palm Room: enter the residence',kind:'door',x:93,z:-23,zone:'ground',spawn:[-26,0]});ring(w,{id:'exit-west-north',label:'North lobby entrance',kind:'door',x:-5.5,z:-20,zone:'grounds',spawn:[-60,-40]});}
 else {ring(w,{id:'residence-exit',label:'Exit to the South Lawn',kind:'door',x:0,z:0,target:'south'});const order:Place[]=['ground','state','second','third'];const index=order.indexOf(zone);if(index<3)ring(w,{id:'stairs-up',label:`Up to the ${floors.find(f=>f.id===order[index+1])?.label}`,kind:'door',x:9,z:zone==='state'?-8:0,zone:order[index+1],spawn:[5,0]});if(index>0)ring(w,{id:'stairs-down',label:`Down to the ${floors.find(f=>f.id===order[index-1])?.label}`,kind:'door',x:-9,z:zone==='state'?-8:0,zone:order[index-1],spawn:[-5,0]});if(zone==='ground')ring(w,{id:'to-west',label:'Palm Room and West Wing',kind:'door',x:-27,z:0,zone:'west',spawn:[91,-23]});for(const x of [-9,9]){for(let step=0;step<5;step++)box(g,x-1+step*.45,.06+step*.08,zone==='state'?-9.6:-1.6,.4,.1+step*.16,1.8,0xdbcbaa);}}
 mergeStatic(g);return w;}


